/* Michele's existing orders, carried over from her Apple Notes. */
window.BLOSSOMS_SEED = [
 {
  "id": "n-9d23e07a0a7c",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-07-21",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "mri",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "July 21 mri",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "reminder",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-43ef3ec2c441",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-07-24",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Daniela Haim",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "6 cupcakes $100 3 blooms. All on instagram",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 10000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/daniela-haim-1.jpg"
  ],
  "thumbUrls": [
   "photos/daniela-haim-1-t.jpg"
  ]
 },
 {
  "id": "n-876adebd5c58",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-07-25",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Alyson — party planner",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "36 cupcakes big rose white with gold tipping peony accented in blush trio, anatomy and white with a blush center, try and figure out little stems. 102 flower with large gold balls as photo and then 36 Oreos",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 154000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-0875c74d6b9d",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-07-30",
  "eventTime": "11:30",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Susan Yates",
  "source": "phone",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "24 cupcake bouquet. Spoke to her on the phone. Picking up around 11:30 from Newport Beach going to Paso Robles — mother's 90th birthday.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 53000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p6e59c8bb",
    "cents": 26500,
    "method": "zelle",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "pickup",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/susan-yates-1.jpg"
  ],
  "thumbUrls": [
   "photos/susan-yates-1-t.jpg"
  ]
 },
 {
  "id": "n-e23010cda732",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-05",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Hallmark",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "200 rice Krispy treats silver, easy sticks, purple bows. 100 Oreo cookies silver. 25 Oreo cookies",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 500000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-59481522064a",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-06",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Janice",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "12 cupcakes, any color",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 16000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p90f57389",
    "cents": 8000,
    "method": "zelle",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-f79cd601524a",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-08",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Natalie",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Everything the same other than 100 pretzels not 200. Total without delivery.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 417000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": true,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "pc3d844d9",
    "cents": 208500,
    "method": "venmo",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/natalie-aug8-1.jpg"
  ],
  "thumbUrls": [
   "photos/natalie-aug8-1-t.jpg"
  ]
 },
 {
  "id": "n-ff432eb29952",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-15",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Cindy and Donald",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-a4165e7af4d4",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-20",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Leila",
  "source": "email",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Wedding cupcakes 7 dozen. Not in individual boxes, just big boxes. Everything is on email.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 112000,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p64a9a317",
    "cents": 56000,
    "method": "zelle",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-0f01ae08917b",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-20",
  "eventTime": "10:00",
  "dateConfirmed": true,
  "altDateNote": "she actually prefers the 21st",
  "name": "Chef Clarisse",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Pull apart bouquet for her daughter. Coming from San Diego, picking up at 10 AM.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 26500,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p6a09257b",
    "cents": 13250,
    "method": "venmo",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "pickup",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/clarisse-1.jpg"
  ],
  "thumbUrls": [
   "photos/clarisse-1-t.jpg"
  ]
 },
 {
  "id": "n-da8c655a7d57",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-08-26",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Karen — wedding",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "One 10 inch, TWO 8 inch, TWO 6 inch, TWO 4 inch. Four dozen cupcakes, all hydrangeas. Green stencil on the 10, one 8, one 6 and one 4. Individual boxes $2.50 each. The 2 4-inch cakes will be guava and funfetti.",
  "avoid": "Not a huge fan of roses — some, but not many. No stencil on the hand-painted cakes.",
  "aboutThem": "She loves lemon curd and guava. Loves the spiky dahlia, peonies, pom-pom dahlia, cascading hydrangeas. Dusty pinks.",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 346000,
  "totalInferred": false,
  "totalHistory": [
   {
    "at": "2026-06-25T00:00:00Z",
    "cents": 358000
   }
  ],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p2dcb0255",
    "cents": 179000,
    "method": "zelle",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "pickup",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/karen-1.jpg",
   "photos/karen-2.jpg"
  ],
  "thumbUrls": [
   "photos/karen-1-t.jpg",
   "photos/karen-2-t.jpg"
  ]
 },
 {
  "id": "n-433c94937657",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-09-12",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Monica",
  "source": "text",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Daughter's wedding, CeeLo farm in Malibu. Everything to be discussed.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "pb37b424c",
    "cents": 133800,
    "method": "zelle",
    "date": "2026-06-01",
    "kind": "deposit"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-4414af3f6898",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-09-19",
  "eventTime": "",
  "dateConfirmed": false,
  "altDateNote": "",
  "name": "Dani",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "love baby shower",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": true,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-18b64c9eec10",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-09-25",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Georgie",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "B day cake, 15 people. Carrot cake, cream cheese filling.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-ba7d5e4d382d",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-10-10",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Natalie",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Fantastic woman, spoke to her for an hour. From Brentwood, was a lawyer now a nurse. Throwing her daughter-in-law and son's wedding at their home. Possibly a big garden table.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 477600,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": true,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p7b65fb87",
    "cents": 250000,
    "method": "zelle",
    "date": "2026-03-30",
    "kind": "deposit"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-730cca7a9e8e",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-11-01",
  "eventTime": "",
  "dateConfirmed": false,
  "altDateNote": "",
  "name": "Susan's son",
  "source": "text",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "Wedding in Palm Springs. 125 individually wrapped cupcakes, 8 inch heart cake with all tulips. All on text.",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": true,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/susans-son-1.jpg"
  ],
  "thumbUrls": [
   "photos/susans-son-1-t.jpg"
  ]
 },
 {
  "id": "n-2fb700f6f807",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-11-07",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Sofia",
  "source": "instagram",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "birthday party",
  "avoid": "",
  "aboutThem": "",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": null,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": null,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [],
  "thumbUrls": []
 },
 {
  "id": "n-53e06fa05108",
  "v": 1,
  "createdAt": "2026-01-01T00:00:00Z",
  "updatedAt": "2026-01-01T00:00:00Z",
  "deletedAt": null,
  "eventDate": "2026-11-15",
  "eventTime": "",
  "dateConfirmed": true,
  "altDateNote": "",
  "name": "Tracy Ingham — wedding",
  "source": "email",
  "handle": "",
  "phone": "",
  "email": "",
  "what": "100 dozen cupcakes and a 6 inch cake. $250 for delivery. Send her an invoice. She has paid in full by Square.",
  "avoid": "Absolutely no pearls — she hates pearls. No orange. No pastels.",
  "aboutThem": "All jewel tones, navy, deep purple. Light peach peonies, white tulips. Gold edible splats around the side — make it visible. Loves palette painting and dimension.",
  "cardMessage": "",
  "photos": [],
  "photoError": false,
  "totalCents": 193300,
  "totalInferred": false,
  "totalHistory": [],
  "deliveryFeeCents": 25000,
  "deliveryTBD": false,
  "noDepositNeeded": false,
  "payments": [
   {
    "id": "p3e4ea82c",
    "cents": 193300,
    "method": "card",
    "date": "2026-05-05",
    "kind": "final"
   }
  ],
  "fulfillment": "",
  "address": "",
  "kind": "order",
  "tentative": false,
  "done": false,
  "doneAt": null,
  "invoicedAt": null,
  "photoUrls": [
   "photos/tracy-1.jpg"
  ],
  "thumbUrls": [
   "photos/tracy-1-t.jpg"
  ]
 }
];
